name: Build and create new release with binaries as assets

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Go binaries with Makefile
      id: build_binaries
      run: |
        git fetch --all
        git fetch --unshallow --tags

        make build-new-version

    - name: Create info for the new release
      id: release_info
      run: |
        releases_base_url="https://github.com/nitschmann/releaser/releases"
        latest_release_url="$releases_base_url/latest"
        latest_release_tag_url=$(curl -Ls -w %{url_effective} -o /dev/null $latest_release_url)
        latest_release_tag=${latest_release_tag_url##*/}
        binary_name="releaser-linux-amd64"
        binary_download_url="$releases_base_url/download/$latest_release_tag/$binary_name"

        curl -o ./releaser -L $binary_download_url
        chmod +x ./releaser

        changelog=$(./releaser changelog)
        new_version=$(./releaser  new-version)
        title=$(./releaser title)

        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}"

        echo ::set-output name=new_version::$new_version
        echo ::set-output name=changelog::$changelog
        echo ::set-output name=title::$title

    - name: Create a new release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_info.outputs.new_version }}
        release_name: ${{ steps.release_info.outputs.title }}
        body: |
          ${{ steps.release_info.outputs.changelog }}

    - name: Upload release asset binary cfdns-darwin-amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/cfdns-darwin-amd64
        asset_name: cfdns-darwin-amd64
        asset_content_type: application/binary

    - name: Upload release asset binary cfdns-linux-386
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/cfdns-linux-386
        asset_name: cfdns-linux-386
        asset_content_type: application/binary

    - name: Upload release asset binary cfdns-linux-amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/cfdns-linux-amd64
        asset_name: cfdns-linux-amd64
        asset_content_type: application/binary

    - name: Upload release asset binary cfdns-linux-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/cfdns-linux-arm
        asset_name: cfdns-linux-arm
        asset_content_type: application/binary

    - name: Upload release asset binary cfdns-linux-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.build/cfdns-linux-arm64
        asset_name: cfdns-linux-arm64
        asset_content_type: application/binary
